[package]
name = "FundFlow"
version = "1.0.0"
authors = ["FundFlow Team"]

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
fundflow = "0x7872e435cfc5150d12070f7f8b638960afa364c9b24c040a960ef8756305eba2"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.25"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "aptos-release-v1.25", subdir = "aptos-move/framework/aptos-token-objects" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "aptos-release-v1.25", subdir = "aptos-move/framework/move-stdlib" }

[dev-dependencies] 