[package]
name = "FundFlow"
version = "0.1.0"
authors = ["FundFlow Team"]

[addresses]
fundflow = "0x1" # This will be replaced with the actual deployment address

[dependencies]
# Movement Labs dependencies will be added here
# For now, we'll use the standard library
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" } 